### ISSUE TITLE
Store files

### ISSUE THREAD

**Issue by mu1664al-s** [careerfairsystems/nexpo-backend#84]
The current system has separate filesystems that can't store and share files anymore. We could store the files as data blob in the database and access them using an access link connected to the user. This can be done completely on back-end without any changes to the front-end.

**Comment by emarforio** [comment]
Was this covered in PR#87? Can we close this?

**Comment by mu1664al-s** [comment]
> Was this covered in PR#87? Can we close this?

Yes
